include: package:effective_dart/analysis_options.yaml
# include: package:lint/analysis_options.yaml
# include: package:pedantic/analysis_options.1.9.0.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    # implicit-dynamic: false
  errors:
    # treat missing required parameters as a warning (not a hint)
    missing_required_param: warning
    # treat missing returns as a warning (not a hint)
    missing_return: warning
    return_of_invalid_type: ignore
    argument_type_not_assignable: ignore

linter:
  rules:
    public_member_api_docs: false
    use_function_type_syntax_for_parameters: true
    prefer_relative_imports: true