name: focus_timer
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.0

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^2.1.0 # null-safety by auto_size_text_pk: ^3.0.0-nullsafety.1
  simple_animations: ^2.5.0 # null-safety with ^3.0.0-nullsafety.2
  # auto_animated: ^2.1.0 # no null-safety
  flutter_icons: ^1.1.0 # null-safety by font_awesome_flutter: ^9.0.0-nullsafety
  # flip_panel: ^1.0.1 # no null-safety
  uuid: ^2.2.2 # no null-safety
  responsive_builder: ^0.3.0 # no null-safety - use fork
  wakelock: ^0.2.1+1 # null-safety with ^0.3.0-nullsafety.1
  background_fetch: ^0.6.0 # no null-safety

  json_annotation: ^3.1.1 # null-safety with ^4.0.0-nullsafety.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0 # null-safety with ^1.0.2

  path_provider: ^1.6.27 # no null-safety
  shared_preferences: ^0.5.12+4 # no null-safety
  supercharged: ^1.12.0 # null-safety with ^2.0.0-nullsafety.1

  provider: ^4.3.3 # null-safety with ^5.0.0-nullsafety.2

  # DB
  sembast: ^2.4.8+1 # null-safety with ^3.0.0-nullsafety.3
  sembast_web: '>=1.0.0' # null-safety with ^2.0.0-nullsafety.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.13
  json_serializable: ^3.5.1 # null-safety with ^4.0.0-nullsafety.0
  mockito: ^4.1.1

  effective_dart: ^1.3.0
  lint: ^1.3.0
  # pedantic: ^1.9.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Consolas
      fonts:
        - asset: fonts/Consolas/Consolas.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
